name: Catalog for WebCatalog

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        submodules: false
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
        architecture: x64
    - run: yarn
    - run: yarn test
    - run: yarn build:pack:webcatalog
    - name: Push metadata to Algolia
      run: yarn build:publish
      env:
        ALGOLIA_APPLICATION_ID: ${{ secrets.WEBCATALOG_ALGOLIA_APPLICATION_ID }}
        ALGOLIA_ADMIN_KEY: ${{ secrets.WEBCATALOG_ALGOLIA_ADMIN_KEY }}
      if: github.event_name != 'pull_request'
    - name: Upload icons to S3
      uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.WEBCATALOG_AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.WEBCATALOG_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.WEBCATALOG_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'dist'
        DEST_DIR: 'apps'
      if: github.event_name != 'pull_request'